spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: maria
    password: mariamaria
  
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: test.admin@gmail.com
    password: test.admin@gmail.com
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    root: info


mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

